### ISSUE TITLE
Check crossSectionScale parameter in the neuroglancer link

### ISSUE THREAD

**Issue by camilolaiton** [AllenNeuralDynamics/aind-ng-link#27]
It is possible that the crossSectionScale is not being assigned in the neuroglancer json that is created through this package.

**Comment by miketaormina** [comment]
Not sure, but I think that this method never reads that value, since there are only specific key inquiries:
https://github.com/AllenNeuralDynamics/aind-ng-link/blob/889948846a5d1887631ba35d7c472c17c426ba3c/src/ng_link/ng_state.py#L303

I think this means that `crossSectionOrientation` is also not parsed (it looks to be absent from pipeline generated viewers)

**Comment by miketaormina** [comment]
I have another thought on this: Since Neuroglancer will ignore JSON keys that it can't use, you could iterate through all available (key, value) pairs and add them to the JSON, which should only fail silently for keys that it can't use. 

Either that, or iterate through each of the following keys:
`title`, `dimensions`, `position`, `crossSectionScale`, `projectionScale`, `layers`, `selectedLayer`, `layout`

**Comment by miketaormina** [comment]
https://github.com/AllenNeuralDynamics/aind-ng-link/pull/28#issue-2371092423

**Comment by camilolaiton** [comment]
Merged, please reopen issue if more problems are found.
